version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      nodejs: 10
  build:
    commands:
      - docker build -t 2donny/beanstalk-fullstack-nginx ./nginx
      - docker build -t 2donny/beanstalk-fullstack-backend ./backend
      - docker build -t 2donny/beanstalk-fullstack-frontend ./frontend

      - docker push 2donny/beanstalk-fullstack-nginx
      - docker push 2donny/beanstalk-fullstack-backend
      - docker push 2donny/beanstalk-fullstack-frontend

artifacts:
  files: imagedefinitions.json
